/// Flutter icons FlickyIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlickyIcons
///      fonts:
///       - asset: fonts/FlickyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FlickyIcons {
  FlickyIcons._();

  static const _kFontFam = 'FlickyIcons';
  static const String? _kFontPkg = null;

  static const IconData ac = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bolt = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fan2 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fan = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flicky = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickylight = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickylogo = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fridge = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hairdrier = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heater = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light2 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light3 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData outlet = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microwave = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oven = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData room = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData union = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
